#!/bin/bash

# We should only run on thul or surt
if [[ $HOSTNAME != "surt.fysik.dtu.dk" && $HOSTNAME != "thul.fysik.dtu.dk" ]] ; then
    echo
    echo "ERROR: You are not on the correct server. Please do"
    echo "          ssh surt.fysik.dtu.dk"
    echo "and try again."
    exit 1
fi

if [[ -z $DISPLAY ]] ; then
    echo
    echo "WARNING: X11 forwarding is not enabled! You cannot run the ase gui."
    echo
    echo "Mac/Linux users: Did you forget -X in your ssh or linuxsh commands?"
    echo "Windows users: Did you use putty instead of MobaXterm?"
    echo
    echo "To continue anyway, press ENTER.  To abort, write quit (or anything else) and then press ENTER"
    read USERINPUT
    if [[ ! -z $USERINPUT ]] ; then
	exit 1
    fi
    echo "OK.  Continuing without X11 support."
fi

if [ "$1"x != "x" ]
then
jupyter notebook --no-browser --port=$1 --ip=$HOSTNAME --notebook-dir=$HOME/batman19 --log-level=INFO 
else
jupyter notebook --no-browser --port=8870 --ip=$HOSTNAME --notebook-dir=$HOME/batman19 --log-level=INFO
fi


